# ------------------------------------------------------------------------
# Behavior: default
#
# * Presets that resemble the original Xiaomi firmware
#   (one group of RGB colors, one group of white light colors)
# * Tapping the power button toggles the light
# * Holding the power button turns on the lamp at very low brightness
# * Tapping the color button activates the next preset
# * Holding the color button activates the next preset group
# * Touching the slider sets the brightness level and turns on the lamp
# * When the light is on, the front panel illumination is on
# ------------------------------------------------------------------------

globals:
  - id: current_brightness
    type: float
    initial_value: "0.0"

script:
  - id: update_front_panel
    mode: restart
    then:
      - front_panel.turn_off_leds: ALL
      - if:
          condition:
            or:
              - text_sensor.state:
                  id: my_light_mode
                  state: rgb
              - text_sensor.state:
                  id: my_light_mode
                  state: white
          then:
            - front_panel.turn_on_leds: [ POWER, COLOR ]
            - front_panel.set_level: !lambda return id(current_brightness);
      - front_panel.update_leds:

light:
  - platform: xiaomi_bslamp2
    id: my_light
    name: ${light_name}
    default_transition_length: ${default_transition_length}

    on_brightness:
      then:
        - globals.set:
            id: current_brightness
            value: !lambda return x;
        - script.execute: update_front_panel

    effects:
      - random:
          name: "Slow Random"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random"
          transition_length: 3s
          update_interval: 3s

    presets:
      rgb:
        red:       { red: 100%, green: 0%,   blue: 0%   }
        green:     { red: 0%,   green: 100%, blue: 0%   }
        blue:      { red: 0%,   green: 0%,   blue: 100% }
        yellow:    { red: 100%, green: 100%, blue: 0%   }
        purple:    { red: 100%, green: 0%,   blue: 100% }
        randomize: { effect: Fast Random                }
      white:
        cold:      { color_temperature: 153 mireds      }
        chilly:    { color_temperature: 275 mireds      }
        luke:      { color_temperature: 400 mireds      }
        warm:      { color_temperature: 588 mireds      }

binary_sensor:
  # Tap = toggle.
  # Hold = turn on at very low brightness.
  - platform: xiaomi_bslamp2
    id: my_power_button
    for: POWER_BUTTON
    on_multi_click:
      - timing:
          - ON for at most 0.8s
        then:
          - light.toggle: my_light
      - timing:
          - ON for at least 0.8s
        then:
          - light.turn_on:
              id: my_light
              brightness: 1%

  # Tap = next preset.
  # Hold = next preset group.
  - platform: xiaomi_bslamp2
    id: my_color_button
    for: COLOR_BUTTON
    on_multi_click:
      - timing:
          - ON for at most 0.6s
        then:
          - preset.activate:
              next: preset
      - timing:
          - ON for at least 0.6s
        then:
          - preset.activate:
              next: group

sensor:
  # Slider now starts at 0.01 because night light mode is disabled.
  - platform: xiaomi_bslamp2
    id: my_slider_level
    range_from: 0.01
    on_value:
      then:
        - light.turn_on:
            id: my_light
            brightness: !lambda return x;

text_sensor:
  - platform: xiaomi_bslamp2
    name: ${light_mode_text_sensor_name}
    id: my_light_mode
